### PR TITLE
Better implentation for ListObjects and ListObjectsV2, including delimiter fuction

### LINKED ISSUE #58: Delimiter functionality for ListObjects and ListObjectsV2 is not working
## Expected Behavior
When using the `delimiter` field in a `ListObjectsV2` call, it should group the result by folders.

## Current Behavior
It's currently ignoring the delimiter field and not grouping the results by folder levels/prefix.

## Possible Solution
Both ListObjects and ListObjectsV2 [here](https://github.com/RTradeLtd/s3x/blob/master/cmd/gateway/s3x/gateway-s3x-object.go#L15) are ignoring the delimiter field.  So assuming the fix here is to take the result and do some parsing on it to group subfolder content by folders and serve that inside the `CommonPrefix` field.

## Steps to Reproduce (for bugs)
1. Create a bucket with a folder A inside and content in that folder
2. Create a subfolder B under folder A and and contents in there as well.
3. Call the list objects API using 
```
var AWS = require('aws-sdk');

var s3 = new AWS.S3({
  accessKeyId: 'minio',
  secretAccessKey: 'miniostorage',
  endpoint: 'http://localhost:9000',
... });

s3.listObjectsV2({
  Bucket: 'bucket-name',
  MaxKeys: 20,
  Delimiter: '/',
}, (err, data) => {
  console.log('res', err, data);
});
```
4. This does not use the delimiter field and the response is not grouped by folders.

## Context
We need to show folder context just for the cbuntu 18.04.3 LTS bionicurrent folder being browsed and this isn't possible without the delimiter field working.  It currently returns all files even in subfolders instead of just the current folder.

## Regression
No

## Your Environment
* Version used (`minio version`): [a85f85c](https://github.com/RTradeLtd/s3x/commit/a85f85cad79df7b60c746c8cd5ec637bc3385e1f) (HEAD -> master, tag: v0.0.7, origin/master, origin/HEAD)
* Environment name and version (e.g. nginx 1.9.1):  n/a
* Server type and version:  n/a
* Operating System and version (`uname -a`): Ubuntu 18.04.3 LTS bionic
* Link to your project: fleek.co

### PR DESCRIPTION
**Pull request by xiegeo**
fixes #58 

## How to test this PR?
~~TODO: add test cases~~

### CODE REVIEW

**Review by bonedaddy — APPROVED** [review]
Looks good, but you need to format some files with `gofmt` first

File: gateway/s3x/gateway-s3x-object.go [hunk 1]
```diff
@@ -11,43 +11,53 @@ import (
...
-	// TODO(bonedaddy): implement complex search (George: prefix implemented)
-	objs, err := x.ledgerStore.GetObjectInfos(ctx, bucket, prefix, "", 0)
+	objs, folders, nextMarker, err := x.ledgerStore.GetObjectInfos(ctx, bucket, prefix, marker, delimiter, maxKeys)
 	if err != nil {
 		return loi, x.toMinioErr(err, bucket, "", "")
 	}
 	loi.Objects = make([]minio.ObjectInfo, 0, len(objs))
 	for _, obj := range objs {
 		loi.Objects = append(loi.Objects, getMinioObjectInfo(&obj))
 	}
```
Comment (bonedaddy) [inline gateway/s3x/gateway-s3x-object.go]: I wonder, should we do:

```

	loi.Objects = make([]minio.ObjectInfo, len(objs))
	for i, obj := range objs {
		loi.Objects[i] = getMinioObjectInfo(&obj)
	}
```

In theory it would be slightly more efficient, since `append` will have to make sure the backing array has enough capacity?

File: gateway/s3x/gateway-s3x-object.go [hunk 2]
```diff
@@ -11,43 +11,53 @@ import (
...
 	ctx context.Context,
 	bucket, prefix, continuationToken, delimiter string,
 	maxKeys int,
 	fetchOwner bool,
 	startAfter string,
-) (loi minio.ListObjectsV2Info, err error) {
-	objs, err := x.ledgerStore.GetObjectInfos(ctx, bucket, prefix, startAfter, 1000)
-	if err != nil {
-		return loi, x.toMinioErr(err, bucket, "", "")
+) (loi2 minio.ListObjectsV2Info, err error) {
```
Comment (bonedaddy) [inline gateway/s3x/gateway-s3x-object.go:47]: How come we need to use `loi2`? Wouldn't we be able to use the objects info returned by `x.ListObject` ?

**Review by bonedaddy — APPROVED** [review]
Looks good! Just 2 questions, but nothing that should block an approval

File: gateway/s3x/gateway-s3x-object.go (hunk 2 above)
Comment (xiegeo) [reply gateway/s3x/gateway-s3x-object.go:47]: ListObjectsV2Info is the required type to fill the interaface.

File: gateway/s3x/gateway-s3x-object.go (hunk 1 above)
Comment (xiegeo) [reply gateway/s3x/gateway-s3x-object.go]: good idea
